# Generated by Django 3.1.5 on 2021-01-25 14:30

from django.db import migrations, models
import gp_blog_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_blog_app', '0007_auto_20210125_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='django.png', upload_to=gp_blog_app.models.user_directory_path),
        ),
    ]
